language: emacs-lisp
env:
  - EMACS=emacs24         PATH="$HOME/.cask/bin:$PATH"
  - EMACS=emacs-snapshot  PATH="$HOME/.cask/bin:$PATH"

install:
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs-snapshot-el emacs-snapshot;
    fi
  - sudo apt-get install texinfo
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

before_script:
  - make env

script:
  - make info
  - make check
